name: jetleaf_retry
description: Resilience module for JetLeaf â€” provides retry, circuit breaker, and fault tolerance patterns.
version: 1.1.1

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_retry
issue_tracker: https://github.com/jetleaf/jetleaf_retry/issues
documentation: https://jetleaf.hapnium.com/docs/resilience

topics:
  - resilience
  - retry
  - fault-tolerance
  - jetleaf
  - circuit-breaker

keywords:
  - jetleaf
  - retry
  - resilience
  - fault-tolerance
  - backoff

environment:
  sdk: ^3.9.0

dependencies:
  meta: ^1.17.0
  jetleaf_lang: ^1.1.1
  jetleaf_logging: ^1.1.1
  jetleaf_pod: ^1.1.1
  jetleaf_core: ^1.1.2

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0